config/routes.rb
TechLocator::Application.routes.draw do

  devise_for :admins

  match '/admin/admins/:id/approve' => 'admins#approve'
  match '/admin/admins/logged_in' => 'admins#logged_in'
  match '/admin/admins/is_superadmin' => 'admins#is_superadmin'
  scope "/admin" do
    resources :admins
  end
  
  match 'location/:id(/:size)/image.jpg' => 'location#showImage'
  match 'location/:id/widget' => 'location#showWidget'
  post 'location/:id/edit' => 'location#update'
  post 'location/new' => 'location#create'
  get "location/:id/delete" => 'location#destroy'
  resources :location

  get "location_changes/index"

  match "/sitemap", :to => "home#sitemap"
  
  root :to => 'home#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/admins/edit.html.haml
= link_to "< back to admins", admins_path

%h2 Edit admin
= semantic_form_for @admin do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :first_name
    = f.input :last_name
    = f.input :organization, hint:"Organization or agency"
    = f.label :location_id, 'Location'
    = f.select :location_id, locationNameList
    = f.input :email, hint:"Email address"
  = f.buttons do
    = f.commit_button :button_html => {:class => "btn btn-primary", :value => "Save"}
    
= button_to "Delete", admin_path(@admin), :method=>:delete, :class => "btn btn-danger"

app/views/admins/index.html.haml
.span10
  %h1 Admins

  %ul.nav.nav-pills
    %li{:class => (params[:approved] != "false" ? "active" : "") }
      = link_to "All", :action => "index" 
    %li{:class => (params[:approved] == "false" ? "active" : "") }
      = link_to "Awaiting approval", :action => "index", :approved => "false"

    .clearfix
    %hr

    %table.table.table-bordered.table-condensed.table-hover
      %thead
        %tr
          %th Name
          %th Email
          %th Organization
          %th Location
          %th Twitter
          %th Approved
          %th Super admin
          %th 
      %tbody
        - unless @admins.nil?
          - @admins.each do |admin|
            %tr
              %td= "#{admin.first_name} #{admin.last_name}"
              %td= link_to admin.email, edit_admin_path(admin)
              %td= admin.organization
              %td= admin.location_link
              %td= admin.twitter_handle
              %td= admin.approved
              %td= admin.superadmin
              %td
                - if current_admin.id == admin.id
                  This is you!
                - else
                  = link_to "Edit", edit_admin_path(admin)
                  - if !admin.approved?
                    |
                    = link_to "Approve", "/admin/admins/#{admin.id}/approve"

app/views/admins/is_superadmin.js.erb
$(document).ready(function() {
  <% if admin_signed_in? %>
    <% if current_admin.try(:superadmin?) %>
      $(".superadmin-edit").show();
    <% end %>
  <% end %>
});

app/views/admins/logged_in.js.erb
$(document).ready(function() {
  <% if admin_signed_in? %>
    $(".admin-edit").show();
  <% end %>
});

app/views/admins/show.html.haml
= link_to "< back to admins", admins_path

%h1 
  = @admin.email

%dl.dl-horizontal
  %dt Approved
  %dd
    = @admin.approved
  %dt Super admin
  %dd
    = @admin.superadmin
  %dt Actions
  %dd
    = link_to "Edit", edit_admin_path(@admin)