config/routes.rb
TechLocator::Application.routes.draw do

  devise_for :admins

  match '/admin/admins/:id/approve' => 'admins#approve'
  match '/admin/admins/logged_in' => 'admins#logged_in'
  match '/admin/admins/is_superadmin' => 'admins#is_superadmin'
  scope "/admin" do
    resources :admins
  end
  
  match 'location/:id(/:size)/image.jpg' => 'location#showImage'
  match 'location/:id/widget' => 'location#showWidget'
  post 'location/:id/edit' => 'location#update'
  post 'location/new' => 'location#create'
  get "location/:id/delete" => 'location#destroy'
  resources :location

  get "location_changes/index"

  match "/sitemap", :to => "home#sitemap"
  
  root :to => 'home#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sitemap
    @locations = Location.all
    respond_to do |format|
      format.xml
    end
  end
end

app/views/home/index.html.haml
- title "Locations"

- content_for :javascripts do
  = javascript_include_tag "home"

.row-fluid
  .span4
    .well
      %h4
        Find near an address 
        <small>(<a id='findMe' href='#'>find me</a>)</small>
      %input.input-block-level#search_address{:placeholder => "Enter an address ...", :type => "text"}
      
      %label
        %select#search_radius.input-small
          %option{:value => "400"} 2 blocks
          %option{:value => "805"} 1/2 mile
          %option{:value => "1610"} 1 mile
          %option{:value => "3220"} 2 miles
        search radius
      
      .pull-right
        %button#view_mode.btn.btn-info 
          Show list
          %i.icon-list.icon-white

      %input#btnSearch.btn.btn-primary{:type => "button", :value => "Search"}
      %button#reset.btn Reset

      .clearfix
      
    .well      
      %p 
        %strong Show me locations that have …
        %br

        %label.checkbox.inline
          %input#filter_internet{:type => "checkbox"}
          %span{:rel => "popover", :"data-content" => "Locations that offer computers with access to the internet.", :"data-original-title" => "<h4>Internet access</h4>"}
            Internet

        %label.checkbox.inline
          %input#filter_training{:type => "checkbox"}
          %span{:rel => "popover", :"data-content" => "Locations that offer training and courses on using computers.", :"data-original-title" => "<h4>Technology training</h4>"}
            Training

        %label.checkbox.inline
          %input#filter_wifi{:type => "checkbox"}
          %span{:rel => "popover", :"data-content" => "Locations that offer free wireless internet access.", :"data-original-title" => "<h4>Wifi</h4>"}
            Wi-Fi
               
      %label 
        %strong and are …
        %select#filter_type.input-block-level
          %option{:value => ""} Any location type
          %option{:value => "Chicago Housing Authority"} Chicago Housing Authority
          %option{:value => "Chicago Public Library"} Chicago Public Library
          %option{:value => "Chicago Public School"} Chicago Public School
          %option{:value => "City Colleges of Chicago"} City Colleges of Chicago
          %option{:value => "Community Technology Center"} Community Technology Center
          %option{:value => "Senior Center"} Senior Center
          %option{:value => "WorkForce Center"} WorkForce Center
          %option{:value => "WorkNet Chicago"} WorkNet Chicago
          %option{:value => "Youth Career Development Center"} Youth Career Development Center
          
      
    %p#resultCount.alert.alert-info.lead

    %p{:style => 'display:none;'}
      %a{:href => '/location/'} Full list of locations &raquo;

  .span8
    #listCanvas{:style => "display: none;"}
      #resultsList
    
    #mapCanvas

app/views/home/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>http://weconnectchicago.org/learn</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>http://weconnectchicago.org/news-events</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>http://weconnectchicago.org/about</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>http://weconnectchicago.org/contact-us</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>

<% @locations.each do |location| -%>
  <url>
    <loc><%= location_url :id => location.slug %></loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
<% end -%>
</urlset>