config/routes.rb
TechLocator::Application.routes.draw do

  devise_for :admins

  match '/admin/admins/:id/approve' => 'admins#approve'
  match '/admin/admins/logged_in' => 'admins#logged_in'
  match '/admin/admins/is_superadmin' => 'admins#is_superadmin'
  scope "/admin" do
    resources :admins
  end
  
  match 'location/:id(/:size)/image.jpg' => 'location#showImage'
  match 'location/:id/widget' => 'location#showWidget'
  post 'location/:id/edit' => 'location#update'
  post 'location/new' => 'location#create'
  get "location/:id/delete" => 'location#destroy'
  resources :location

  get "location_changes/index"

  match "/sitemap", :to => "home#sitemap"
  
  root :to => 'home#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/location.rb
class Location
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Callbacks
  extend ActiveModel::Naming
    
  validates_presence_of :organization_name, :organization_type, :org_phone, :address, :city, :state, :zip_code
  # validates_format_of :agency_staff_person_contact_email, :location_leadership_email, :pcc_staff_person_email, 
  #                     :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i,
  #                     :allow_nil => true, :allow_blank => true
  
  define_model_callbacks :create, :save
  after_save    :bust_cache
  after_create  :bust_cache
  
  def create_method( name, &block )
    self.class.send( :define_method, name, &block )
  end

  def create_attr( name )
    create_method( "#{name}=".to_sym ) { |val| 
      instance_variable_set( "@" + name, val)
    }

    create_method( name.to_sym ) { 
      instance_variable_get( "@" + name ) 
    }
  end
  
  
  def [](attr)
    self.send(attr)
  end

  def []=(attr, val)
    create_attr(attr.to_s) unless respond_to?(attr)  # initialize new attrs on the fly
    self.send("#{attr}=", val)
  end
  
  def initialize(attributes = {})
    #read in a hash of attributes from Fusion Tables and set them as attributes of the model
    #for more, see http://railscasts.com/episodes/219-active-model
    attributes.each do |name, value|
      name = "#{name}"
      create_attr name
      instance_variable_set("@" + name.to_s, value)
    end
  end
  
  def to_fusion_format
    # return the object as a hash, suitable for saving to Google Fusion Tables
    self.instance_variables.inject({}) do |memo, v|
      k = v.to_s.gsub(/@/, '')
      memo[k.to_sym] = send(k)
      memo
    end
  end
  
  def create
    table = GData::Client::FusionTables::Table.new(FT, :table_id => APP_CONFIG['fusion_table_id'], :name => "My table")
    column_names = FT.execute("SELECT * FROM #{APP_CONFIG['fusion_table_id']} LIMIT 1;").first.collect{|k,v| k }    
    new_values = self.to_fusion_format.delete_if{ |k,v| !column_names.include?(k) }    
    table.insert new_values #saves to Fusion Tables    
  end
  
  def save
    # save the record to Fusion Tables
    table = GData::Client::FusionTables::Table.new(FT, :table_id => APP_CONFIG['fusion_table_id'], :name => "My table")
    row_id = FT.execute("SELECT ROWID FROM #{APP_CONFIG['fusion_table_id']} WHERE slug = '#{slug}';").first[:rowid]
    column_names = FT.execute("SELECT * FROM #{APP_CONFIG['fusion_table_id']} LIMIT 1;").first.collect{|k,v| k }
    
    new_values = self.to_fusion_format.delete_if{ |k,v| !column_names.include?(k) }
    table.update row_id, new_values  # saves to Fusion Tables
  end
  
  def persisted?
    false
  end
  
  def self.all    
    collection = []
    results = Rails.cache.fetch("all-locations", :expires_in => 12.hours) do
      FT.execute("SELECT * FROM #{APP_CONFIG['fusion_table_id']} ORDER BY organization_name;")
    end
    
    results.each do |result|
      collection << Location.new(result)
    end
    collection
  end
  
  def bust_cache
    Rails.cache.delete("all-locations")
  end
  
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show, :showImage, :showWidget]
  before_filter :set_location, :only => [:show, :edit]
  # caches_action :showImage
  caches_action :show, :layout => false
  caches_action :index, :layout => false

  def index
    @locations = Location.all
  end

  def show
    respond_to do |format|
      format.html  # show.html.haml
      format.json  { render :json => @location }
    end
  end

  def showImage
    require 'open-uri'
    location = fetch params[:id]
    featured_photo = getFlickrFeaturedPhoto(location.flickr_tag)
    unless featured_photo.nil?
      url = URI.parse(getFlickrPhotoPath(featured_photo, params[:size]))
      open(url) do |http|
        response = http.read
        render :text => response, :status => 200, :content_type => 'image/jpeg'
      end
    else
      send_data File.read("#{Rails.root}/app/assets/images/placeholder.jpg", :mode => "rb"), :status => 200, :content_type => 'image/jpeg'
    end
  end

  def showWidget
    @location = fetch params[:id]
    
    respond_to do |format|
      format.html  { render :template => "location/widget", :layout => false }
      format.json  { render :json => @location }
    end
  end
  
  def new
    location_edit = fetch_empty
    @location = Location.new(location_edit)
  end

  def create
    @location = Location.new(params[:location])
    
    # location_edit = fetch_empty
    @location = set_changes(@location, params)

    # fill in read-only values
    # FIXME: move to model
    @location[:id] = get_new_id
    @location[:slug] = to_slug "#{@location[:organization_name]} #{@location[:address]}"
    @location[:flickr_tag] = to_flickr_tag "pcc-#{@location[:organization_name]} #{@location[:id]}"
    
    # FT has some problems with empty fields. clearing them out
    # @location.each do |name, value|
    #   if value == ''
    #     location_edit.delete("#{name}".to_sym)
    #   end
    # end
    
    if @location.valid?
       # expire cache
       expire_action :action => :index

      # save to location_changes tracking table
      save_location_changes({"Location created" => ""})

      begin
        @location.create
        flash[:notice] = "Location created successfully!"
      rescue StandardError => e
        flash[:notice] = "There was a problem creating this location. Please try again or contact the system administrator."
        Rails.logger.error("[LocationController#create] error saving new item: #{e.message}")
        Rails.logger.error("[LocationController#create] error message:\n\n #{e.backtrace.join("\n")}")                
      end
      redirect_to location_path :id => @location.slug
    else
       render :action => 'new'
    end

  end

  def edit
    @location_title = @location[:organization_name]
  end

  def update
    # fetch the existing data from Fusion Tables (this it probably redundant)
    @location = fetch params[:id]
    @location_title = @location[:organization_name]

    # stuff in new values from the form in to the Fusion Table hash object
    change = {}
    params[:location].each do |name, value|
      old_value = "#{@location["#{name}".to_sym]}"
      # if a field has changed, add it to the change hash for location_changes tracking
      if old_value != value
        change["#{name}"] = [old_value, value]
      end
    end

    @location = set_changes(@location, params)

    Rails.logger.debug 'changes!'
    Rails.logger.debug change.inspect
    if @location.valid? && change.length > 0
      # expire cache
      expire_action :action => :show
      expire_action :action => :index

      # save to location_changes tracking table
      save_location_changes(change)

      begin
        @location.save # saves to Fusion Tables
        flash[:notice] = "Location saved successfully!"
      rescue StandardError => e
        Rails.logger.error("[LocationController#update] error saving update: #{e.message}")
        Rails.logger.error("[LocationController#update] error message:\n\n #{e.backtrace.join("\n")}")        
        flash[:notice] = "There was a problem saving this location. Please try again or contact the system administrator."
      end
      redirect_to location_path :id => @location.slug
    else
      render :action => 'edit'
    end
  end

  def destroy
    if current_admin.try(:superadmin?)
      expire_action :action => :show
      expire_action :action => :index

      begin
        @location = fetch params[:id]
        # save to location_changes tracking table
        save_location_changes({"Location deleted" => ""})

        table = fetch_table
        row_id = fetch_row_id @location.slug
        table.delete row_id
        flash[:notice] = "Location deleted successfully!"
        redirect_to root_path
      rescue
        flash[:notice] = "There was a problem deleting this location. Please try again or contact the system administrator."
        redirect_to location_path :id => @location.slug
      end
    else
      flash[:notice] = "You must be a super admin to delete locations."
      redirect_to location_path :id => @location.slug
    end
  end

  private

  def fetch_table
    GData::Client::FusionTables::Table.new(FT, :table_id => APP_CONFIG['fusion_table_id'], :name => "My table")
  end

  def fetch_empty
    # fetch a row to get the column names and set to blank
    location_edit = FT.execute("SELECT * FROM #{APP_CONFIG['fusion_table_id']} LIMIT 1;").first || not_found
    location_edit.each do |k, v|
      location_edit[k] = ''
    end
    location_edit
  end

  def fetch(slug)
    location = FT.execute("SELECT * FROM #{APP_CONFIG['fusion_table_id']} WHERE slug = '#{slug}';").first
    location.present? ? Location.new(location) : nil
  end

  def fetch_row_id(slug)
    FT.execute("SELECT ROWID FROM #{APP_CONFIG['fusion_table_id']} WHERE slug = '#{slug}';").first[:rowid]
  end

  def set_location
    @location = fetch(params[:id]) || not_found
    @page_title = @location.organization_name
  end

  def set_changes(location_edit, params)
    # stuff in new values from the form in to the Fusion Table hash object
    params[:location].each do |name, value|
      old_value = "#{location_edit["#{name}".to_sym]}"
      # if a field has changed, add it to the change hash for location_changes tracking
      if old_value != value
        location_edit.send("#{name}=", value)
      elsif old_value == '' && value == ''
        # location_edit.delete("#{name}".to_sym)
      end
    end

    # special logic for un-editable fields
    if location_edit[:org_phone] != nil and location_edit[:org_phone] != ''
      location_edit[:org_phone] = location_edit[:org_phone].gsub /[^0-9x]/, ''
    end
    location_edit[:full_address] = "#{location_edit[:address]} #{location_edit[:city]}, #{location_edit[:state]} #{location_edit[:zip_code]}"
    
    # geocode lat/lng
    if location_edit[:full_address] != nil and location_edit[:full_address] != ''
      require 'geocoder'
      lat, long = Geocoder.coordinates(location_edit[:full_address]) 
      location_edit[:latitude] = "#{lat}"
      location_edit[:longitude] = "#{long}"
    end

    # urls
    location_edit[:website] = add_http location_edit[:website]
    location_edit[:training_url] = add_http location_edit[:training_url]

    location_edit
  end

  def save_location_changes(changes)
    @location_changes = LocationChanges.new(:admin_id => current_admin.id,
                                              :location_id => @location.id,
                                              :name => @location.organization_name,
                                              :slug => @location.slug,
                                              :change => changes.to_json)
    @location_changes.save
  end

  def get_new_id
    id = FT.execute("SELECT id FROM #{APP_CONFIG['fusion_table_id']} ORDER BY id DESC LIMIT 1;").first[:id]
    id.to_i + 1
  end

  def add_http url
    if not (url.nil? || url == '')
      if not url.match(/^https?:\/\//)
        url = 'http://' + url
      end
    else
      url = ''
    end
    url
  end

  def to_slug s
    #strip the string
    ret = s.strip.downcase

    #blow away apostrophes
    ret.gsub! /['`.]/,""

    # @ --> at, and & --> and
    ret.gsub! /\s*@\s*/, " at "
    ret.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
     ret.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '-'  

     #convert double underscores to single
     ret.gsub! /_+/,"_"

     #strip off leading/trailing underscore
     ret.gsub! /\A[_\.]+|[_\.]+\z/,""

     ret
  end

  def to_flickr_tag(s)
    n = 3 #num words 
    s = s.split[0...n].join(' ')
    #strip the string
    ret = s.strip.downcase

    #blow away apostrophes
    ret.gsub! /['`.]/,""

    # @ --> at, and & --> and
    ret.gsub! /\s*@\s*/, " at "
    ret.gsub! /\s*&\s*/, " and "

    #replace all non alphanumeric, underscore or periods with underscore
     ret.gsub! /\s*[^A-Za-z0-9\.\-]\s*/, '-'  

     #convert double underscores to single
     ret.gsub! /_+/,"_"

     #strip off leading/trailing underscore
     ret.gsub! /\A[_\.]+|[_\.]+\z/,""

     ret
  end
end

app/views/location/_form.html.haml
= simple_form_for(:location, :html => { :class => 'form-horizontal' }) do |f|
  - unless @location.errors.messages.length == 0
    .alert.alert-error.fade.in
      %a.close{"data-dismiss" => "alert", :href => "#"} &times;
      %h4 Plese review the following errors:
      %ul
      - @location.errors.messages.each do |error|
        %li 
          = "#{error[0].to_s.humanize} #{error[1][0]}"

  %fieldset
    %legend Basic information
    = f.input :organization_name, :input_html => {:class => 'span12'}
    = f.input :organization_type, :collection => ["Chicago Housing Authority", "Chicago Public Library", "Chicago Public School", "City Colleges of Chicago", "Community Service Center", "Community Technology Center", "Senior Center", "WorkForce Center", "WorkNet Chicago", "Youth Career Development Center"]
  
    = f.input :org_phone, :label => "Phone", :hint => "Formatting will be provided automatically"
    = f.input :hours, :required => false, :input_html => {:class => 'span12'}
    = f.input :website, :required => false, :input_html => {:class => 'span12'}

  %fieldset
    %legend Address
    = f.input :address, :input_html => {:class => 'span12'}, :label => 'Street address'
    = f.input :room_list, :input_html => {:class => 'span12'}, :label => 'Room number(s)', :required => false, :hint => 'Room or suite numbers for on-site public computer lab(s)'

    = f.input :city, :input_html => {:class => 'span5'}
    = f.input :state, :input_html => {:class => 'span1'}
    = f.input :zip_code, :input_html => {:class => 'span3'}

  %fieldset
    %legend Description
    = f.input :friendly_description, :as => :text, :hint => "A few sentences describing this location and its environment", :input_html => {:rows => 5, :class => 'span12'}, :required => false 
      
  %fieldset
    %legend Features

    /TODO: format these checkboxes to fit on one line
    = f.input :internet, :as => :boolean
    = f.input :training, :as => :boolean
    = f.input :wifi, :as => :boolean
    / = f.input :october_open_house, :as => :boolean

    = f.input :pc_use_restrictions, :as => :text, :required => false, :input_html => {:rows => 5, :class => 'span12'}, :input_html => {:rows => 5, :class => 'span12'}
    = f.input :hardware_public, :input_html => {:class => 'span2'}, :hint => "Number of public computers available", :required => false
    = f.input :assistive_technology, :as => :text, :hint => "Software for aiding the blind or disabled", :required => false, :input_html => {:rows => 5, :class => 'span12'}
    = f.input :internet_upload, :input_html => {:class => 'span2'}, :required => false
    = f.input :internet_download, :input_html => {:class => 'span2'}, :required => false
    = f.input :public_wifi_detail, :as => :text, :hint => "Wifi encryption (if any), other notes about wifi", :required => false, :input_html => {:rows => 5, :class => 'span12'}
    = f.input :time_allowed_per_user, :collection => ["Timed", "Unlimited"], :required => false
    = f.input :time_allowed_per_user_detail, :hint => "Time in minutes if there is a limit", :required => false
    = f.input :handicap_access_detail, :hint => "Details for handicap accessibility", :required => false, :as => :text, :input_html => {:rows => 5, :class => 'span12'}

  %fieldset
    %legend Training
    / = f.input :training_types, :hint => 'Type of training offered. Example: Digitial Skills Initiative, Cyber Navigator', :required => false
    = f.input :training_headline, :hint => 'If training is offered, the name of the training program', :required => false
    = f.input :training_description, :hint => 'If training is offered, a description of the training program', :required => false, :as => :text, :input_html => {:rows => 5, :class => 'span12'}
    = f.input :training_url, :hint => 'If training is offered, website for more information', :required => false

  %fieldset
    %legend Transportation
    = f.input :nearest_parking, :collection => ["Free", "Paid"], :required => false
    = f.input :nearest_parking_detail, :hint => "Details and directions for nearest parking lot", :required => false
    = f.input :public_transportation_detail, :hint => "Details and directions for nearest CTA or Metra stations or bus stops", :required => false

  %fieldset
    %legend Volunteers
    = f.input :volunteers_used, :as => :boolean
    = f.input :volunteers_used_how, :hint => "If volunteers are used, for what purpose?", :required => false, :as => :text, :input_html => {:rows => 5, :class => 'span12'}
    = f.input :volunteers_wanted_how, :hint => "If volunteers are needed, for what purpose?", :required => false, :as => :text, :input_html => {:rows => 5, :class => 'span12'}
      
  %fieldset
    %legend Personnel contact
    .form-inputs.row
      = f.input :location_leadership, :required => false, :wrapper_html => {:class => "span6"}, :label => "Location leadership", :hint => "Name"
      = f.input :location_leadership_email, :required => false, :wrapper_html => {:class => "span6"}, :label => false, :hint => "Email"
    .form-inputs.row
      = f.input :agency_leadership_contact, :required => false, :wrapper_html => {:class => "span6"}, :label => "Agency leadership", :hint => "Name"
      = f.input :agency_staff_person_contact_email, :required => false, :wrapper_html => {:class => "span6"}, :label => false, :hint => "Email"
    .form-inputs.row
      = f.input :pcc_staff_person, :required => false, :wrapper_html => {:class => "span6"}, :label => "PCC staff person", :hint => "Name"
      = f.input :pcc_staff_person_email, :required => false, :wrapper_html => {:class => "span6"}, :label => false, :hint => "Email"
    
    = f.input :twitter_handle, :required => false
 
  %hr
    = f.button :submit


/ id - can't edit
/ checked - hidden
/ notes
/ slug - can't edit
/ tecservicesid - can't edit
/ organization_name
/ organization_type
/ full_address - generated based on other fields
/ address
/ city
/ state
/ zip_code
/ org_phone
/ hours
/ website - url
/ appointment
/ internet
/ wifi
/ training
/ pc_use_restrictions
/ hardware_public
/ assistive_technology
/ internet_upload
/ internet_download
/ volunteers_used
/ volunteers_used_how
/ volunteers_wanted_how
/ public_wifi_detail
/ nearest_parking
/ nearest_parking_detail
/ public_transportation_detail
/ time_allowed_per_user
/ time_allowed_per_user_detail
/ room_list
/ handicap_access_detail
/ friendly_description
/ agency_leadership_contact
/ agency_staff_person_contact_email
/ twitter_handle
/ training_types
/ flickr_tag - can't edit
/ training_headline
/ training_description
/ training_url - url
/ october_open_house
/ location_leadership
/ location_leadership_email
/ pcc_staff_person
/ pcc_staff_person_email
/ latitude - geocoded based on saved address
/ longitude - geocoded based on saved address

app/views/location/edit.html.haml
- title "Edit '#{@location_title}'"
%h2
  Edit
  = "'#{@location_title}'"

%p 
  %abbr{:title => "required" } *
  \= required field

.row-fluid
  .span7
    = render "location/form"
    %a.btn{:href => "/location/#{params[:id]}"} Cancel

  .span5
    .well
      %h3 Additional details

      %dl.dl-horizontal
        %dt
          Id
        %dd
          = @location.id
        %dt
          Tec Services Id
        %dd
          = @location.tecservices_id
        %dt
          URL
        %dd
          %a{:href => "http://locations.weconnectchicago.org/#{@location.slug}"}
            = "http://locations.weconnectchicago.org/#{@location.slug}"
        %dt
          Flickr tag
        %dd
          %a{:href => "http://www.flickr.com/photos/tags/#{@location.flickr_tag}/"}
            = @location.flickr_tag
        %dt
          Location (lat/lng)
        %dd
          = "#{@location.latitude}, #{@location.longitude}"

app/views/location/index.html.haml
%h1 All locations

- @locations.each do |location|
  .row-fluid.item-list
    .span8
      %a{:href => "/location/#{location[:slug]}"}
        %span.lead
          = location[:organization_name]
      %br
      = location[:organization_type]
      %br
      = formatAddress location[:address], location[:city], location[:state], location[:zip_code], ''
      %br
      - unless location[:hours].nil?
        = location[:hours]

app/views/location/new.html.haml
- title "New location"
%h2
  New location

%p 
  %abbr{:title => "required" } *
  \= required field

.row-fluid
  .span7
    = render "location/form"
    %a.btn{:href => "/"} Cancel

  .span5
    .well
      %h3 Generated fields

      %p
        When you create a new location, some fields will be populated for you. They are:

      %ul
        %li Id
        %li Url
        %li Flickr tag
        %li Latitude and longitude

app/views/location/show.html.haml
- page_layout "container"
:javascript 
  $(function(){
    MapsDetailLib.initializeMap();
  
    if (MapsDetailLib.map != null)
      MapsDetailLib.displayPoint("#{encodeAddress(@location.full_address)}");
  });

%script{:src => "/admin/admins/logged_in.js", :type => "text/javascript"}
%script{:src => "/admin/admins/is_superadmin.js", :type => "text/javascript"}
.row{:itemscope => '', :itemtype => "http://schema.org/Place"}
  .span7
    %h2
      %span{:itemprop => "name"}= @location.organization_name
      %small.admin-edit{:style => 'display: none;'}
        %a{:href => "/location/#{params[:id]}/edit"} 
          %i.icon-pencil
          Edit
        %a.superadmin-edit{:href => "/location/#{params[:id]}/delete", :style => 'display: none;', :onclick => "return confirm('Are you sure want to delete this location?');"} 
          %i.icon-remove
          Delete
    %p.lead
      = @location.organization_type

    %p
      / AddThis Button BEGIN
      .addthis_toolbox.addthis_default_style
        %a.addthis_button_facebook_like{"fb:like:layout" => "button_count"}
        %a.addthis_button_tweet
      :javascript
        var addthis_config = {"data_track_addressbar":false};
      %script{:src => "http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-5023cf8c771737b1", :type => "text/javascript"}
      / AddThis Button END
    .row  
      .span4
        %p  
          = formatAddress @location.address, @location.city, @location.state, @location.zip_code, @location.room_list
          %span{:itemprop => 'geo', :itemscope => '', :itemtype => 'http://schema.org/GeoCoordinates', :style => "display:none"}
            %span{:itemprop => 'latitude'}= @location.latitude
            %span{:itemprop => 'longitude'}= @location.longitude
          
        %p 
          - unless @location.org_phone == ''
            %span{:itemprop => "telephone"}= number_to_phone((@location.org_phone.gsub /[^0-9x]/, ''), :area_code => true)
          - unless @location.website == ''
            %br
            %span{:itemprop => 'url', :style => "display:none;"}= @location.website
            %a{:href => @location.website}
              = snippet @location.website

          - unless @location.pcc_staff_person == ''
            %br
              Administrator:  
              = formatContact @location.pcc_staff_person, @location.pcc_staff_person_email
              
        - unless @location.hours == ''
          %p
            Hours:  
            = @location.hours
    
      .span3  
        %table.table.table-bordered
          %thead
            %tr
              %th Internet
              %th Training
              %th Wi-Fi
              
          %tbody
            %tr
              %td
                = yes_no_icon @location.internet
              %td
                = yes_no_icon @location.training
              %td
                = yes_no_icon @location.wifi
    .row
      .span7
        - unless @location.friendly_description == ''
          %hr
          %h4 About this place
          %p{:itemprop => 'description'}
            = @location.friendly_description
        
        - unless @location.training_headline == ''
          %hr
          %h4 
            Training
          %h5
            = @location.training_headline
          %p
            = @location.training_description

        - unless @location.hardware_public == '' 
          %hr
          %h4 
            Additional info
            
          %dl.dl-horizontal
            - unless @location.hardware_public == ''  
              %dt
                Computers
              %dd
                = @location.hardware_public
                computers available to the public
                
            - unless @location.internet_upload == ''
              %dt 
                Internet speed
              %dd
                Upload: 
                = @location.internet_upload 
              %dd
                Download: 
                = @location.internet_download 
              
            - unless @location.pc_use_restrictions == ''
              %dt 
                Use restrictions
              %dd 
                = @location.pc_use_restrictions
            
            - unless @location.assistive_technology == ''
              %dt 
                Assistive tech
              %dd 
                = @location.assistive_technology 
            
            - unless @location.time_allowed_per_user == ''
              %dt 
                Time restrictions
              %dd
                = @location.time_allowed_per_user 
              %dd
                = @location.time_allowed_per_user_detail
                
    .row.hidden-phone
      .span7
        %hr
        %h4 
          Photos of 
          = @location.organization_name
        %ul.thumbnails#gallery{:"data-toggle" => "modal-gallery", :"data-target" => "#modal-gallery"}
          - getFlickrGalleryPhotos(@location.flickr_tag).each do |photo|
            %li.span1
              %a.thumbnail{:href => getFlickrPhotoPath(photo, 'z'), :rel =>"gallery", :title => "#{photo.title}"}
                %img{:src => getFlickrPhotoPath(photo, 's')} 

        %p
          Have a photo for this location? Upload it to
          %a{:href => "http://flickr.com"} Flickr
          and tag it with
          %strong
            = @location.flickr_tag
                
  .span5
    .well
      %p
        - featured_photo = getFlickrFeaturedPhoto(@location.flickr_tag)
        - unless featured_photo.nil?
          %img.img-polaroid{:src => "/location/#{params[:id]}/image.jpg", :title => @location.organization_name, :alt => @location.organization_name, :itemprop => 'image'}

      #mapDetail
      %hr
      %p.lead
        = formatAddress @location.address, @location.city, @location.state, @location.zip_code, ''
      %p
        %a.btn.btn-success{:href => "https://maps.google.com/maps?f=d&hl=en&geocode=&daddr=#{encodeAddress(@location.full_address)}"}
          Get directions
          %i.icon-white.icon-arrow-right
          
      
      %dl.dl-horizontal
        - unless @location.nearest_parking == ''
          %dt
            Nearest parking 
          %dd
            = @location.nearest_parking
          %dd
            = @location.nearest_parking_detail
        
        - unless @location.public_transportation_detail == ''
          %dt
            Public transit
          %dd 
            = @location.public_transportation_detail
            
        - unless @location.handicap_access_detail == ''
          %dt
            Handicap access
          %dd 
            = @location.handicap_access_detail

      %hr
      %h4 Do you help manage this location? 
      %p
        = link_to('Sign up to be a Connect Chicago admin', new_admin_registration_path)
        and update this page anytime you want!

#modal-gallery.modal.modal-gallery.hide.fade
  .modal-header
    %a.close{"data-dismiss" => "modal"} x
    %h3.modal-title
  .modal-body
    .modal-image
  .modal-footer
    %a.btn.btn-info.modal-download{:target => "_blank"}
      %i.icon-download
      %span Download
    %a.btn.modal-prev
      %i.icon-arrow-left.icon-white
      %span Previous
    %a.btn.modal-next
      %span Next
      %i.icon-arrow-right.icon-white
    