config/routes.rb
TechLocator::Application.routes.draw do

  devise_for :admins

  match '/admin/admins/:id/approve' => 'admins#approve'
  match '/admin/admins/logged_in' => 'admins#logged_in'
  match '/admin/admins/is_superadmin' => 'admins#is_superadmin'
  scope "/admin" do
    resources :admins
  end
  
  match 'location/:id(/:size)/image.jpg' => 'location#showImage'
  match 'location/:id/widget' => 'location#showWidget'
  post 'location/:id/edit' => 'location#update'
  post 'location/new' => 'location#create'
  get "location/:id/delete" => 'location#destroy'
  resources :location

  get "location_changes/index"

  match "/sitemap", :to => "home#sitemap"
  
  root :to => 'home#index'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta(name="google-site-verification" content="97Jq6z293C73QwTFJHshmEDl_6jI8bXvyRDm70scPmE")
    %title= @page_title ? "#{@page_title} - Connect Chicago" : "Connect Chicago"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    :css
      @import url('https://fonts.googleapis.com/css?family=Quattrocento+Sans:400,400italic,700,700italic');
    = content_for :stylesheets
    
    %link(href="/favicon.ico" rel="shortcut icon")

    = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false" 
    = javascript_include_tag "application"

  %body
    .container
      %a{:href => APP_CONFIG['domain']}
        %img.logo{:src => "/assets/logo.png", :alt => "Connect Chicago"}
      .navbar
        .navbar-inner
          .container

            / .btn-navbar is used as the toggle for collapsed navbar content
            %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

            .nav-collapse
              %ul.nav
                %li
                  %a{:href => APP_CONFIG['domain']} Home
                %li{:class => (controller?("location") || controller?("home")) ? "active" : ""}
                  %a{:href => "/"} Locations
                %li
                  %a{:href => APP_CONFIG['domain'] + "learn"} Learn
                %li
                  %a{:href => APP_CONFIG['domain'] + "news-events"} News &amp; Events
                %li
                  %a{:href => APP_CONFIG['domain'] + "about"} About
                %li
                  %a{:href => APP_CONFIG['domain'] + "contact-us"} Contact Us

              %ul.nav.pull-right
                - if admin_signed_in?
                  - if current_admin.try(:superadmin?)
                    %li
                      = link_to('New', location_new_path)
                    %li{:class => controller?("admins") ? "active" : ""}
                      = link_to('Admins', admins_path)
                    %li{:class => controller?("location_changes") ? "active" : ""}
                      = link_to('Changes', location_changes_index_path)
                  %li{:class => controller?("devise/registrations") ? "active" : ""}
                    = link_to('Account', edit_admin_registration_path)
                  %li
                    = link_to('Logout', destroy_admin_session_path, :method => :delete)        
                - else
                  %li
                    = link_to('Login', new_admin_session_path)

    %div{:class => content_for?(:page_layout) ? content_for(:page_layout) : "container"}
      .content
        - flash.each do |name, msg|
          %div#flash{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
            %a.close{"data-dismiss" => "alert"} &#215;
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
        = yield
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = content_for :javascripts
    
    = javascript_include_tag "analytics_lib" if Rails.env.production?